name: Build & Push Docker

on:
  push:
    paths: [ "nginx-app/**" ]
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t nivbadasshboss/custom-nginx:latest ./nginx-app
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker push nivbadasshboss/custom-nginx:latest
